import {it,expect} from 'vitest';import {readFile} from 'node:fs/promises';import {mergeSources,validate,finalize,normalizeId} from './core.mjs';
const gp=JSON.parse(await readFile('.work/gp.json','utf8'));
it('normalizes provider prefixes',()=>{expect(normalizeId('gemini/gemini-3.8-flash','google')).toBe('gemini-3.8-flash');expect(normalizeId('xai/grok-4.7','x-ai')).toBe('grok-4.7')});
it('adopts higher price and records conflicts',()=>{const lite={'gpt-6-luna':{litellm_provider:'openai',input_cost_per_token:2e-6,output_cost_per_token:1e-6}};const models={openai:{models:{'gpt-6-luna':{cost:{input:1,output:3}}}}};const d=mergeSources(lite,models,gp);const m=d.providers[0].models[0];expect(m.prices.input_mtok).toBe(2);expect(m.prices.output_mtok).toBe(3);expect(d.conflicts).toHaveLength(2)});
it('maps context tiers with greater-than boundary',()=>{const d=mergeSources({}, {openai:{models:{'gpt-6-luna':{cost:{input:1,output:2,tiers:[{input:3,tier:{type:'context',size:272000}}]}}}}},gp);expect((d.providers[0].models[0].prices.input_mtok as any).tiers[0].start).toBe(271999)});
it('output version remains stable and validation catches bad prices and drops',async()=>{const d=JSON.parse(await readFile('data/prices.json','utf8'));expect(finalize(d,d)).toBe(d);const bad=structuredClone(d);bad.providers[0].models[0].prices.input_mtok=-1;expect(()=>validate(bad)).toThrow('invalid price');const drop=structuredClone(d);drop.providers[0].models=drop.providers[0].models.slice(0,2);expect(()=>validate(drop,d)).toThrow('model count dropped')});
it('maps per-pixel image variants and resolution video rates',()=>{const lite={
 'high/100-x-200/gpt-image-test':{litellm_provider:'openai',mode:'image_generation',input_cost_per_pixel:.000001},
 'gemini/veo-test':{litellm_provider:'gemini',mode:'video_generation',output_cost_per_second:.05,output_cost_per_second_1080p:.08}
 };const d=mergeSources(lite,{},gp);expect(d.providers.find(p=>p.id==='openai')!.models.find(m=>m.id==='gpt-image-test')!.x_extra_prices.per_image['100x200/high']).toBeCloseTo(.02);expect(d.providers.find(p=>p.id==='google')!.models.find(m=>m.id==='veo-test')!.x_extra_prices.per_video_second['1080p']).toBe(.08)});

it('does not duplicate existing image extractor mappings',()=>{const d=mergeSources({}, {},gp);const google=d.providers.find(p=>p.id==='google')!;const ex=google.extractors!.find(e=>e.api_flavor==='default')!;expect(ex.mappings.filter(m=>m.dest==='output_image_tokens')).toHaveLength(1)});
